services:
  - type: web
    name: expo-metro-server
    env: node
    buildCommand: npm install
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    plan: starter

